### ISSUE TITLE
Stress names incorrect in output .e files in Norma

### ISSUE THREAD

**Issue by ikalash** [lxmota/Norma.jl#19]
They look as follows currently:

![image](https://github.com/user-attachments/assets/912e3e00-b5af-4d68-a628-8acf2669fdb9)

**Comment by lxmota** [comment]
I put in a fix. Let's see if that works.

**Comment by ikalash** [comment]
I have verified that these look correct now.  Thanks for fixing it @lxmota !

**Comment by ikalash** [comment]
Reopening since this is still happening.  It is particularly bad for the new Schwarz notched cylinder problem:

![image](https://github.com/user-attachments/assets/712d553c-ccc3-4a4a-82b7-6cbfcb3dd377)

**Comment by lxmota** [comment]
I'm unable to reproduce this. In what machine are you running? Maybe we should meet to debug this.

**Comment by ikalash** [comment]
Interesting.  This is on my RHEL8 workstation. I thought it was a paraview version issue (I am using Paraview 5.6.2) but if I look at the .e file that gets dumped, it is messed up there: 

```
 name_elem_var =
  "stress_xx_1<\201%P?\2509\030\352\257KP?\3501\n",
    ":\034\177",
  "stress_yy_1",
  "stress_zz_1",
  "stress_yz_1",
  "stress_xz_1\210\222\206W?",
  "stress_xy_1\317\003\354a\277\372~j\274t\223x?\3302\n",
    ":\034\177",
  "stress_xx_2<\201%P?\2509\030\352\257KP?\b3\n",
    ":\034\177",
  "stress_yy_2",
  "stress_zz_2",
  "stress_yz_2",
  "stress_xz_2\210\222\206W?",
  "stress_xy_2\322\2361P?",     
```
Yes, we can look at this together.  I should have some availability in the late afternoon - will send you a Calendar invite.

**Comment by lxmota** [comment]
It looks like this is an issue with Exodus.jl, which I have reported here:

https://github.com/cmhamel/Exodus.jl/issues/202#issue-2685087209

**Comment by cmhamel** [comment]
@ikalash could you let me know the output of 

'''pkg> status'''

After starting julia with

'''julia --project=@.'''

In the norma directory?

**Comment by ikalash** [comment]
It gives the following:

```
(Norma) pkg> status
Project Norma v0.1.0
Status `~/Norma.jl.clean/Project.toml`
  [8bb1440f] DelimitedFiles v1.9.1
  [b7d42ee7] Einsum v0.4.1
  [f57ae99e] Exodus v0.13.6
  [1fa38f19] Format v1.3.7
  [0c5d862f] Symbolics v6.22.0
  [ddb6d928] YAML v0.4.12
  [37e2e46d] LinearAlgebra v1.11.0
  [de0858da] Printf v1.11.0
  [9a3f8284] Random v1.11.0
  [2f01184e] SparseArrays v1.11.0
  [8dfed614] Test v1.11.0
```

**Comment by ikalash** [comment]
@cmhamel : that's interesting.  @lxmota I say maybe lets stick with 11.1 and wait for a bug fix.  Do you agree with this?

@cmhamel I am happy to provide instructions to reproduce the issue.

**Comment by cmhamel** [comment]
> @cmhamel : that's interesting.  @lxmota I say maybe lets stick with 11.1 and wait for a bug fix.  Do you agree with this?
> 

I'm doubtful Norma uses any of the new features in 1.11 so I recommend sticking with 1.10 for the time being. Not just because 9f the exodus bug, but also because there were some performance regressions in 1.11 that I and others have noticed.

**Comment by lxmota** [comment]
On macos I have not noticed this Exodus issue, but I have confirmed it on Linux, so perhaps we can install Julia 1.10 aside Julia 1.11 to avoid this issue.

**Comment by ikalash** [comment]
Ok.  I think I will keep Julia 11.1 on my current machine camobap but I will install Julia 10.1 on my new workstation that will be ready to use / start setting things up on hopefully later this week.

Lets keep this issue open I guess?

**Comment by cmhamel** [comment]
@lxmota @ikalash I just released Exodus.jl 0.13.7 which fixes this issue. CI is passing on Linux/mac/windows for julia 1.10 and 1.11.

**Comment by ikalash** [comment]
@cmhamel : I just checked with julia-10 and julia-11 and the weird strings for the stress names have gone away, so I believe the issue is fixed.  Thank you!  I will go ahead and close.
