### ISSUE TITLE
Is there a way to get the subdomain ID (or name of yaml file) that is currently being worked on in Norma routines?

### ISSUE THREAD

**Issue by ikalash** [lxmota/Norma.jl#22]
Perhaps this can be obtained from the mesh::ExodusDatabase?  It would be convenient to access it in routines like apply_bcs().

**Comment by lxmota** [comment]
The ExodusDataBase type has a field called file_name::String as indicated here:
https://github.com/cmhamel/Exodus.jl/blob/master/src/ExodusTypes.jl#L238
So in norma one could do something like:
println(mesh.file_name)

**Comment by ikalash** [comment]
Good to know.  Thank you for looking into it!  I will close the issue.
